id: I79F870C7
legacy_id: P003296
ocr_import_info:
  bdrc_scan_id: W20509
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:21:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:32:56.897465+00:00'
last_modified: 2022-09-01 21:33:08.085723
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W20509
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW20509
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མགུར་འབུམ། བྱ་བྲལ་ངག་དབང་རྣམ་རྒྱལ།
  author: བྱ་བྲལ་ངག་དབང་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.6523506266863218
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I1KG9700:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9700
      total_pages: 500
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9700.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6523506266863218
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
