id: P003296
initial_creation_type: ocr
source_metadata:
  id: bdr:W20509
  title: མགུར་འབུམ། བྱ་བྲལ་ངག་དབང་རྣམ་རྒྱལ།
  author: ''
  volumes:
    a0048ee505d84be3971ce8d34a23d3d2:
      image_group_id: I1KG9700
      title: ''
      volume_number: 1
      total_pages: 500
      base_file: v001.txt
